### PR TITLE
Fix Docker build with network-interfaces version 1.2

### LINKED ISSUE #43: franka-lightweight-interface not working
Recent changes have caused the franka-light-weight-interface not to build anymore:
https://github.com/epfl-lasa/franka-lightweight-interface

Any idea how this can be fixed?

### PR DESCRIPTION
**Pull request by domire8**
This should fix aica-technology/network-interfaces#43

If you could test this please.

### CODE REVIEW

**Comment by niederha** [comment]
So I don't know the frame work well. But I tested quickly the fix with @Elise-J . If I understood correctly, it turns out that our franka is not compatible with libfranka 0.9.0. We tried switching to .0.8.0 the build fails with network-interface v1.2.

I might have missed something, but it looks like something is not right.

**Comment by domire8** [comment]
Ah too bad, I was afraid of that. I have no idea why the 0.8.0 tag of libfranka would not build, but I will look into it. I'm not sure how it is related to network interfaces, because it shouldn't... Thanks for the feedback

**Comment by niederha** [comment]
Yeah I think it might be worth it that either @liuyangdh or @Maxime00 take a look at that they are more aware of the whole framwork. I had to do some urgent work on the franka. And I patched some things a bit randomly but I suspect there might be an issue that brakes the compilation with network interface later than 1.1.0 or something. If no one answers within the week, I'll investigate more.

**Comment by nash169** [comment]
In order to use the latest libfranka you have to update the controller board on the franka. I did not do it when I worked with it because this would mess up the configuration of a lot of people working with it. The 0.8 libfranka builds. You just have to fix a  couple of headers path. Although I never used to this repo but only libfranka on its own; so I cannot tell if there is any another issue in this repo.

**Comment by domire8** [comment]
> The 0.8 libfranka builds. You just have to fix a couple of headers path. 

I agree that this is the issue, just sucks if you check out a tagged version and it doesn't even build :smile:

**Comment by domire8** [comment]
Ok, I found the nearest commit after 0.8.0 tag in libfranka that fixes the include problem. Should be fine now, to be tested again

**Comment by nash169** [comment]
I think I even open a pr on libfranka. No idea why they never bothered to fix it since a lot of people are still using the 0.8 version.

**Comment by domire8** [comment]
Any updates here? Were you able to test this?

**Comment by Maxime00** [comment]
Tested just now, this fixes the build issue

**Pull request merged**
